### ISSUE TITLE
the Breast Cancer Wisconsin dataset is not available

### ISSUE THREAD

**Issue by gash717** [rasbt/python-machine-learning-book#2]
In chapter6, the Breast Cancer Wisconsin dataset is not available now.
Maybe it is broken link.

currently
```
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data', header=None)
```

should be
```
df = pd.read_csv('http://mlr.cs.umass.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data', header=None)
```

I'm sorry if I'm wrong.

**Comment by cligini** [comment]
You are definitely right Masahiro Nomura, it appears the top level site is
not responding to pings at all from the looks of it. Both encrypted and
unencrypted channels are not responding. More digging can be done though.
It may just be that it does not respond to that protocol.

**Comment by rasbt** [comment]
Thanks for the @gash717 Like @cligini mentioned, there seems to be a (hopefully temporary) issue with UCI's ML repository. For cases like that, I put the datasets into the 
[https://github.com/rasbt/python-machine-learning-book/tree/master/code/datasets](https://github.com/rasbt/python-machine-learning-book/tree/master/code/datasets) directory here on GitHub. 

So, in order to be able to load the dataset, you could do

`df = pd.read_csv('https://raw.githubusercontent.com/rasbt/python-machine-learning-book/master/code/datasets/wdbc/wdbc.data', header=None)`

I will add a note in the notebooks to mention it to the users/readers.

Thanks!

**Comment by rasbt** [comment]
Okay, I added notes to the respective IPython notebooks so that people can fetch the datasets from this GitHub repo until the UCI dataset repository are resolved. 

The links to the datasets are:

- **Wisconsin Breast Cancer Dataset:** 'https://raw.githubusercontent.com/rasbt/python-machine-learning-book/master/code/datasets/wdbc/wdbc.data'
- **Iris:**  'https://raw.githubusercontent.com/rasbt/python-machine-learning-book/master/code/datasets/iris/iris.data'
- **Housing:** 'https://raw.githubusercontent.com/rasbt/python-machine-learning-book/master/code/datasets/housing/housing.data'
- **Wine:** 'https://raw.githubusercontent.com/rasbt/python-machine-learning-book/master/code/datasets/wine/wine.data'

Thanks again for pointing it out!

**Comment by rasbt** [comment]
Just checked back on this issue, and seems that UCI's Machine Learning Repository is back online. So, the datasets should be accessible via their original links again (e.g., https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data). However, it's definitely not a bad thing to have the alternative links in the IPython notebooks now ;)

**Comment by gash717** [comment]
I was able to confirm it now.
Thank you very much :-D
