### ISSUE TITLE
Add Code Examples

### ISSUE THREAD

**Issue by andrelip** [rasbt/python-machine-learning-book#21]
Just bought this book and I can't find the source code of the examples in the book. I bought on Amazon and gone to Packtpub page as suggested on the book but even the zip I download from them is only a mirror to this repository. Just images, no code for the examples in the book. It's really annoying to have to type every single example by hand.

**Comment by rasbt** [comment]
Thanks for your interest in my book and sorry for the trouble. But don't worry, there's no need to type everything up manually, the code is all in this github repository in the `./code` subdirectory :). So, once you downloaded the .zip version, you have to go inside this `code` directory`, and then go the respective chapter. Inside the e.g., ch01 directory, you will then find an Jupyter notebook with the code. (Alternatively, I provided the code as py script files in the `code/_convenience_scripts` subdirectory; however, I really recommend the Jupyter notebooks since I also have the chapter headings, a table of contents, and the images in there alongside the code. 

![screen shot 2016-07-12 at 10 15 18 pm](https://cloud.githubusercontent.com/assets/5618407/16790827/9fd59cbc-487e-11e6-9cbe-fb048f02deb3.png)

![screen shot 2016-07-12 at 10 15 27 pm](https://cloud.githubusercontent.com/assets/5618407/16790829/a3092872-487e-11e6-8939-b087b96c8438.png)

![screen shot 2016-07-12 at 10 15 35 pm](https://cloud.githubusercontent.com/assets/5618407/16790833/a7828394-487e-11e6-9ef2-d3c25a50cee3.png)

Alternatively, you can also view the notebooks online if you don't want to use Jupyter notebooks on your machine. For example, you can simply click on the respective chapter (I provided links in the README.md file):


![screen shot 2016-07-12 at 10 20 57 pm](https://cloud.githubusercontent.com/assets/5618407/16790913/5b49c162-487f-11e6-9bfb-5c054d151bde.png)

![screen shot 2016-07-12 at 10 24 35 pm](https://cloud.githubusercontent.com/assets/5618407/16790931/7fe2276c-487f-11e6-8537-64cc75194373.png)

Please let me know how it goes, I am more than happy to help you out here :)

**Comment by andrelip** [comment]
Sorry. It was correct.
I never learned python and tried to follow the book as the sintax seems very close to other dynamic languages like Ruby and is very explict while importing modules like Elixir and ES2015. I expected to have a couple .py files and when I opened the notebook archive in vim and saw all the markups I thought it was just a revision for the chapter. Thanks for the awesome book and to spend your time taking those pics!

**Comment by rasbt** [comment]
You are very welcome! I am glad to hear that you got the Jupyter notebooks to work. 

> I expected to have a couple .py files

Btw. I recently created these :). They are in the [./code/optional-py-scripts](https://github.com/rasbt/python-machine-learning-book/tree/master/code/optional-py-scripts) directory in this repo. However, I would really recommend using the Jupyter notebooks instead since they are easier to read (because of the chapter and section headlines, and the inline plots).
