### ISSUE TITLE
mlxtend no longer has tf_classifier

### ISSUE THREAD

**Issue by anyaconda** [rasbt/python-machine-learning-book#72]
I wanted to run your code that compares TensorFlow with SKLearn but it no longer works. 
https://github.com/rasbt/python-machine-learning-book/blob/master/faq/tensorflow-vs-scikitlearn.md

In addition, your mlxtend package no longer has tf_classifier and consequently no TfSoftMaxRegression.

Would you have an updated resource by any chance?

**Comment by rasbt** [comment]
I've removed the TensorFlow code from mlxtend because it became pretty inconvenient to maintain. The original code should still be available through GitHub. E.g., if you install mlxtend 0.5.1, (`pip install mlxtend=0.5.1`) or browse through the files here: https://github.com/rasbt/mlxtend/tree/86e40d5af5222d78acf219cc8188cfd28a972d9e/mlxtend/tf_classifier

**Comment by anyaconda** [comment]
Makes sense.  Thank you for a quick reply, Sebastian.  I'll browse your
book for other examples.
Anya

On Sun, Jul 22, 2018 at 8:09 AM, Sebastian Raschka <notifications@github.com

**Comment by rasbt** [comment]
Sounds good :). I will close this thread for now, but pls let me know if you have any further questions
