### ISSUE TITLE
Notebook error

### ISSUE THREAD

**Issue by einsteniano4000** [rasbt/python-machine-learning-book#81]
Opening the first chapter file ch01.ipynb result in the following error:

"Unreadable Notebook: /home/antonio/libro-machine-learning/ch01.ipynb NotJSONError("Notebook does not appear to be JSON: '\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang...")"

python version: 3.7 from anaconda distribution.

**Comment by rasbt** [comment]
Hi there. This error typically happens if you incorrectly download the notebook. I.e., it looks like you used the browser's "save as" function to save the notebook, which will just save a copy of the HTML page and not the notebook itself. 

There are many ways for downloading a notebook, I recommend the simplest one, i.e., downloadng the whole repo:

![Screen Shot 2020-01-05 at 3 28 16 PM](https://user-images.githubusercontent.com/5618407/71786345-16c60280-2fd0-11ea-9730-8e175dcda9be.png)

**Comment by einsteniano4000** [comment]
Thanks. I used a massive downloader plugin of the browser.
