### ISSUE TITLE
IndexError: too many indices for array in CH-5 PCA Plot Code 

### ISSUE THREAD

**Issue by somesh636** [rasbt/python-machine-learning-book#82]
I am having an issue in executing the for generating the graph of the PCA in Chapter-5 of the book Python Machine Learning. I tried debugging but I am not able to understand what the problem in the code is.
![issue1](https://user-images.githubusercontent.com/15856787/74785512-81798780-5278-11ea-8f06-52e1de87e6a6.png)
Kindly provide support for this issue.

**Comment by rasbt** [comment]
There error means that `X_train_pca` has either 0 or 1 dimensions, instead of 2, or there is only 1 column instead of 2. You can double-check by executing `print(X_train_pca.shape)` before the for loop. The returned tuple should have at least 2 numbers, where the second number should be a 2.   

This if you see that `X_train_pca.shape` is not `(100, 2)`, then there is a typo somewhere in your preceding code.

**Comment by somesh636** [comment]
Thank you for your quick response. There was a typo in the code. 
This book is really good for understanding the Machine learning concepts.

**Comment by rasbt** [comment]
glad to hear that you found and fixed it!
